kind: pipeline
type: docker
name: default

steps:

- name: build-push
  image: golang:1.11
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
    - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/semantic-release-plugin ./"
  when:
    event:
      exclude:
      - tag

- name: get-version
  image: node:14-alpine
  environment:
    NODE_PATH: "/usr/local/lib/node_modules"
  commands:
    - "sh ./scripts/install.sh"
    - "mkdir /semantic-release && cp default.config.js /semantic-release/"
    - "mkdir /bin && cp release/linux/amd64/semantic-release-plugin /bin/"
  when:
    event:
      exclude:
      - tag

