kind: pipeline
type: docker
name: default

steps:

- name: get-branch-version
  image: smoothify/drone-semantic-release
  settings:
    dry_run: true
    git_credentials: { from_secret: git_password }
    git_user_email: drone@radiantflow.net
    tags_build: true
  when:
    event:
      - push

- name: build-branch
  image: golang:1.11
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
    - export NEXT_VERSION="$(cat .release-version 2>/dev/null || echo "${DRONE_COMMIT_SHA:0:8}" )"
    - "go build -v -ldflags \"-X main.version=${NEXT_VERSION}\" -a -tags netgo -o release/linux/amd64/semantic-release-plugin ./"
  when:
    event:
      - push

- name: build-branch-image
  image: plugins/docker
  settings:
    repo: smoothify/drone-semantic-release
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    cache_from:
      - smoothify/drone-semantic-release:latest
  when:
    event:
      - push

- name: release-branch
  image: smoothify/drone-semantic-release
  settings:
    dry_run: false
    git_credentials: { from_secret: git_password }
    git_user_email: { from_secret: git_email }
    changelog: true
    package_json: true
  when:
    event:
      - push
