kind: pipeline
type: docker
name: default

steps:

- name: build-push
  image: golang:1.11
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
    - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/semantic-release-plugin ./"
  when:
    event:
      - push

- name: build-branch
  image: plugins/docker
  settings:
    repo: smoothify/drone-semantic-release
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    tag:
      - ${DRONE_BRANCH/#master/latest}
    cache_from:
      - smoothify/drone-semantic-release:latest
  when:
    event:
      - push

- name: release-branch
  image: smoothify/drone-semantic-release
  settings:
    dry_run: false
    git_login: { from_secret: git_username }
    git_password: { from_secret: git_password }
    git_user_email: { from_secret: git_email }
    changelog: true
    package_json: true
  when:
    event:
      - push
